# Generated by Django 2.2.1 on 2021-02-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('search_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('search_time', models.TimeField()),
                ('temperature', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
